class_name RoomManager extends Node;

# The size of the grid generated by the RoomManager
const GRID_SIZE: int = 5;
# The random factor of the direct path generation from start to goal
const PATH_GENERATION_RANDOM_FACTOR: float = 0.3;
# The random factor of branching after path generation
const BRANCH_GENERATION_RANDOM_FACTOR: float = 0.2;
# The max branch length
const MAX_BRANCH_LENGTH: int = 2;

# Stores whether the room is a START, GOAL STATE, or lowkey chill with it
enum ROOM_TYPE {START, GOAL, NEITHER};

# The root node of the graph generated.
var root: Room;
# The "end room" (goal state)
var goal_state: Room;
# The grid used for generation.
var grid = [];

func generate_grid():
	# init empty arr
	for i in range(GRID_SIZE):
		grid.append([]);
		for j in range(GRID_SIZE): grid[i].append(ROOM_TYPE.NEITHER);
	
	# start is always top left
	grid[0][0] = ROOM_TYPE.START;
	
	# randomly pick a corner for the GOAL
	var corner = randi() % 3;
	match corner:
		0:
			# top right
			grid[0][GRID_SIZE - 1] = ROOM_TYPE.GOAL;
		1:
			# bottom left
			grid[GRID_SIZE - 1][0] = ROOM_TYPE.GOAL;
		2:
			# bottom right
			grid[GRID_SIZE - 1][GRID_SIZE - 1] = ROOM_TYPE.GOAL;
	



func _ready():
	generate_grid();
	return
	
