class_name RoomManager extends Node;

# The size of the grid generated by the RoomManager
const GRID_SIZE: int = 5;
# The random factor of the direct path generation from start to goal
const PATH_GENERATION_RANDOM_FACTOR: float = 0.3;
# The random factor of branching after path generation
const BRANCH_GENERATION_RANDOM_FACTOR: float = 0.2;
# The max branch length
const MAX_BRANCH_LENGTH: int = 2;

# Stores whether the room is a START, GOAL STATE, or lowkey chill with it
enum ROOM_TYPE {START, GOAL, NEITHER};

# The root node of the graph generated.
var root: Room;
# The adjacency list of the graph.
var node_graph = [];
# The "end room" (goal state)
var goal_state: Room;
# The grid used for generation.
var grid = [];

# ROOM resource.
const ROOM = preload("uid://nwhqrixlnb1d");

# Makes a GRID_SIZE x GRID_SIZE grid for graph initialization.
func _generate_grid():
	# init empty arr
	for i in range(GRID_SIZE):
		grid.append([]);
		for j in range(GRID_SIZE): grid[i].append(ROOM_TYPE.NEITHER);
	
	# start is always top left
	grid[0][0] = ROOM_TYPE.START;
	
	# randomly pick a corner for the GOAL
	var corner = randi() % 3;
	match corner:
		0:
			# top right
			grid[0][GRID_SIZE - 1] = ROOM_TYPE.GOAL;
		1:
			# bottom left
			grid[GRID_SIZE - 1][0] = ROOM_TYPE.GOAL;
		2:
			# bottom right
			grid[GRID_SIZE - 1][GRID_SIZE - 1] = ROOM_TYPE.GOAL;

# Helper for grid conversion to graph.
func _grid_point_to_node(i, j):
	# 4-direction neighbors
	var top;
	var bottom;
	var left;
	var right;
	
	if (i != 0): top = grid[i - 1][j];
	if (i != GRID_SIZE - 1): bottom = grid[i + 1][j];
	if (j != 0): left = grid[i][j - 1];
	if (j != GRID_SIZE - 1): right = grid[i][j + 1];
	
	# create da node now
	var res: Room = ROOM.instantiate();
	res.neighbors = [top, left, bottom, right];
	return res;

# Create the graph (array of Rooms, storing neighbors inside).
func _grid_to_graph():
	for i in range(GRID_SIZE):
		for j in range(GRID_SIZE):
			node_graph[i*GRID_SIZE + j] = _grid_point_to_node(i, j);
	
func _ready():
	_generate_grid();
	_grid_to_graph();
	
